language: node_js
node_js:
  - node
script: >
    npm run travis-tests # &&
    # gzip -c built/winamp.js > built/winamp.js.gz &&
    # python node_modules/travis-weigh-in/weigh_in.py built/winamp.js &&
    # python node_modules/travis-weigh-in/weigh_in.py built/winamp.js.gz
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - rm .gitignore
  - ./scripts/bust.sh
deploy:
    verbose: true
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    on:
        branch: master
